spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reservation_system?serverTimezone=UTC&charactorEncoding=UTF-8
    username: nayoung
    password: nayoung1234